### ISSUE TITLE
Support proxy contracts?

### ISSUE THREAD

**Issue by dabbott** [iainnash/ether.actor#14]
It would be useful if I could use ether.actor to call proxied contract functions. E.g. when I use https://github.com/iainnash/gwei-slim-erc721, I'm not to call functions that only exist in the base implementation contract. 

I'm not sure if/how this would work, but off the top of my head:
- Is there a way to identify contracts like this, to follow the `implementation` address and concat that ABI?
- Or maybe I can pass the ABI of the function to call somehow?

**Comment by iainnash** [comment]
Added proxy results @dabbott
