### ISSUE TITLE
Can you support BSC and BscTestnet?

### ISSUE THREAD

**Issue by xinsxxx** [iainnash/ether.actor#17]
Can you support BSC and BscTestnet?

**Comment by iainnash** [comment]
Sure!

What's a good node provider for BSC?

I'll look into it early next wk.

**Comment by xinsxxx** [comment]
> Sure!
> 
> What's a good node provider for BSC?
> 
> I'll look into it early next wk.

That's Great！Thank you！

The provider for BSC on official docs:
https://docs.binance.org/smart-chain/developer/rpc.html

"
https://bsc-dataseed.binance.org/
https://bsc-dataseed1.defibit.io/
https://bsc-dataseed1.ninicoin.io/
"

And the bsc-connector:
https://yarnpkg.com/package/@binance-chain/bsc-connector

Hope it is useful to you.

**Comment by xinsxxx** [comment]
https://www.npmjs.com/package/@dgate/bsc

**Comment by xinsxxx** [comment]
JSON-RPC methods
Please refer to this [wiki page](https://github.com/ethereum/wiki/wiki/JSON-RPC) or use Postman: https://documenter.getpostman.com/view/4117254/ethereum-json-rpc/RVu7CT5J?version=latest

**Comment by iainnash** [comment]
Done :D

**Comment by xinsxxx** [comment]
Can not open "https://bsc-testnet.ether.actor/"

**Comment by iainnash** [comment]
Must’ve typoed a DNS configuration.

**Comment by xinsxxx** [comment]
> DNS configuration

My DNS configuration is OK, you can have a try to open  "https://bsc-testnet.ether.actor/".

**Comment by iainnash** [comment]
I was meaning my internal dns / ssl setup.

**Comment by iainnash** [comment]
Thank you this is good :)
