### ISSUE TITLE
Testnets are not working

### ISSUE THREAD

**Issue by jeevatrippy** [iainnash/ether.actor#21]
Hi hope you are doing good.

Testnet links are not working,

To fetching contract json mainnet is working fine
https://ether.actor/0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63.json

But testnet is not working
https://rinkeby.ether.actor/0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63.json 

Please help me with this.

Thank you.

**Comment by dr-data** [comment]
@iainnash , I think the testnet work API related code doesn't work? 

Also, would you mind to post the example of the .env file setting so that I can host the mirror of the https://ether.actor

**Comment by jeevatrippy** [comment]
@dr-data 
Thanks for your reply,
I didn't use the code, I have directly got the infos from URL.
https://goerli.ether.actor/0xc00771F7dC9662B1F5bFA1A1dA5D3854596E1e90.json

The contract is verified, but I got the following error.

{"statusCode":404,"message":"Contract not verified","error":"Not Found"}

Please help me.

Thank you.

**Comment by iainnash** [comment]
@jeevatrippy Hey! I wasn't getting notified here. Will look into it.

**Comment by iainnash** [comment]
I've rebooted the node, updated API keys and everything works again @jeevatrippy

**Comment by iainnash** [comment]
@dr-data I can add an example .env file here for you.
