### ISSUE TITLE
'Contract not verified' on Polygon

### ISSUE THREAD

**Issue by scottincrypto** [iainnash/ether.actor#28]
I'm getting  `{"statusCode":404,"message":"Contract not verified","error":"Not Found"}` errors when trying to call functions on Polygon.  Here are a couple which have verified contracts on Polygonscan:

https://polygon.ether.actor/0x3A58a54C066FdC0f2D55FC9C89F0415C92eBf3C4/totalSupply
https://polygon.ether.actor/0xBA12222222228d8Ba445958a75a0704d566BF2C8/getPoolTokens/0xb20fc01d21a50d2c734c4a1262b4404d41fa7bf000000000000000000000075c

Any ideas on resolving this?

**Comment by iainnash** [comment]
Most likely an API key issue. Looking into it now.

**Comment by iainnash** [comment]
Fixed :)

**Comment by scottincrypto** [comment]
Fantastic, thank you!
