### ISSUE TITLE
[New Chain] : Support of Arbitrum

### ISSUE THREAD

**Issue by NelsonRodMar** [iainnash/ether.actor#35]
Gm 

I'm using ether.actor and would love to have the support of Arbitrum.

**Comment by NelsonRodMar** [comment]
I've created a PR to add Arbitrum, waiting for review and accept : https://github.com/iainnash/ether.actor/pull/36

**Comment by iainnash** [comment]
Hi! Haven't seen this, would be glad to add.

**Comment by NelsonRodMar** [comment]
Ahah no worries, everything should be good to be merged !

**Comment by Burberrysmart** [comment]
forge verify-contract 0x324eca20b358b18e48f2611f7452560ce3b3c1bb src/ContractFile.sol:ContractName --verifier etherscan --verifier-url "https://api.etherscan.io/v2/api?chainid=2201" --etherscan-api-key YourEtherscanApiKey --watch

**Comment by Burberrysmart** [comment]
This is to add support of Arbitrum
